dist: trusty
sudo: false

branches:
  except:
  - pretest
  - elec

language: C

script:
    - make -C tests/blink/
    - make -C tests/led/
    - make -C tests/ranging/
    - make -C tests/coding_wheels/
    - make -C tests/cam

cache: ccache

addons:
    apt:
        packages:
        - gcc-arm-none-eabi
        - libnewlib-arm-none-eabi
        - libopencv-dev
        - libcv-dev
