branches:
    except:
    - pretest
    - elec

sudo: required

language: C

script:
    - cd tests/blink/
    - make

cache: ccache

addons:
    apt:
        sources:
        - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
        packages:
        - gcc-arm-embedded
