dist: trusty
sudo: true

branches:
  except:
  - pretest
  - elec

language: C

script:
    - make -C tests/blink/
    - make -C tests/led/
    - make -C tests/ranging/
    - make -C tests/coding_wheels/
    - cd opencv
    - mkdir build && cd build
    - cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..
    - make -j 8
    - sudo make install
    - cd ../..
    - export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
    - make -C tests/cam/

cache: ccache

addons:
    apt:
        packages:
        - gcc-arm-none-eabi
        - libnewlib-arm-none-eabi
